---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapp
  labels:
    app: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      name: helloworldapp
      labels:
        app: dummy
    spec:
      containers:
      - image: neetimunshi/helloworld-neeti
        name: helloworldapp
        ports:
        - name: helloworldapp
          containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: helloworldapp
  labels:
    app: dummy
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30009
  selector:
    app: dummy
